apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    credentials: AgBE76gAscSXw0LL9RqePEATLCiLgwHz8mjG6UFirD16ggvBCroDfRbP3BBS5eeCD0omTiVeeArK+6/rDfQW/gD+9OJx7PdafkMyXlMmnnK0OPMN9F3vT4hlsd4ypTlSC06FBTK5JOR2hGelGpGtYzXTd9Krgc1ysjAd6TbgL/wu3Vl63VjpyYWRV3DAf7KF3Z6IhLSg5pDCKlfjbV3VUBSbWajQOfAHzoalc61DaMzQ1ZPVG9tm/k9oMHyXBuKWqEjDQD9Ivf8tYZnGLjU9xgQ0f3Ol6tKfXnU0/jG2zPVPuNBo+T8SOCZhGn/UQlrde7z3FUtBbUYTbVH6KcjBZqZ0VNaxd3SQP4GJrQOw/n1o0I9JrqgjJdMMjs9DWFFxIkZh29YhcO8IDsmotthsNYSNHlDihhWzt9kj3q+9eUMA13kVGr+0RuA8pC4boo9Xsk4EatDmytlil+He1i5ffHWpwu9MZG6GSo8ikOYwBv1gENhD7nxr5phzExfvj5QVpx8E6BcBRz2Q1sDsCvD6LVszHA0TY2VpoVnS+t0soh8DILSPUY1Y2Fx+sichAuOywkoTulC2oKNXKRxZH58HUgIrrWnC9ldm+0ZbAmAmQkwYTEt7DgIwvZNvWsj3rcuJv4UzNpoZI62/YPUIgnfJ3fqyid1LnEfpmtOQCvNZepXgANi6SIVZciOhD/vZ+Smk9W6iEcgNe4t1Q9DB9ovdBa4MEAwIa5u15qDbrJdAFwoRJjE2iHNDzxkPt/eEJQntt/WJr1OBd/mCgaFcHL8AXqKBzQfKSv+AoTe7WusLXDQTdnI7W/e6kEBRLG6+7B0OmjTRS2Nj1hTT65HIBPukhNcQT55cbgPL/vvemQ9ZItYYOXcHhpISod3V7e1fSh49QZXKNy+8/g3aB70tcwFOBhjiguyk6jZhqYZ1sLmWhrKVXoDC3DsD4NBWQTg2KmSTg+xWrR+/NrJdSIA9zdSzqYeOIRRMTaTvdIEvQZrL0DiKA9/7Tr8HaqG23p4lSAsjS5RiG19AEy4K9P/tvBGD85A46vHLIOvlkK6MrTrAa5oe4ZzmGvG4Q5pjT6TG4kxn+rN/EyaOMOAnhiyR6dCKJS30vtN+ePlnVDWwtJqRtFKqfaIOxgkl0lO+bESVfWMTqNAAeg8VOFxv2g==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaque

